export { default as ExamplesOfProjects } from "shared/components/sections/Main/ExamplesOfProjects/ExaplesOfProjects";
export { default as HomeIntro } from "shared/components/sections/Main/HomeIntro/HomeIntro";
export { default as AboutIntro } from "shared/components/sections/About/AboutIntro/AboutIntro";
export { default as AboutInfo } from "shared/components/sections/About/AboutInfo/AboutInfo";
export { default as ConsultIntro } from "shared/components/sections/Consult/ConsultIntro/ConsultIntro";
export { default as ConsultThemes } from "shared/components/sections/Consult/ConsultThemes/ConsultThemes";
export { default as WhyMe } from "shared/components/sections/Consult/WhyMe/WhyMe";
export { default as ConsultFeedback } from "shared/components/sections/Consult/ConsultFeedback/ConsultFeedback";
export { default as ConsultPrices } from "shared/components/sections/Consult/ConsultPrices/ConsultPrices";
